### Key repository sample (Streams API)

This is a dummy sample of a bank account. Each account has an associated
key to encrypt all operations associated to the account.

For this account, we manage the bank view and the agency view.

* The bank has access to the full key repository (acount 0 to 9).
* Agency 1 has only access to a subset of key repository (account 0 to 4)
* Agency 2 has only access to a subset of key repostory (account 5 to 9)

All operations are written encrypted into a common topic `operations`

#### Running the sample

[source,indent=0]
....
cd samples/kafkastream-with-keyrepo-sample
docker-compose up # on windows and OSX, you need to adjust
sh generateKeys.sh
sh runSamples.sh
....

include::../../doc/running-docker-kafka.adoc[]

#### Usage


##### Sample Main

[source,java,indent=0]
....
include::./src/main/java/io/quicksign/kafka/crypto/samples/stream/keyrepo/SamplesMain.java[tags=main]
....

##### Producer side

.SampleProducer.java
[source,java,indent=0]
....
include::./src/main/java/io/quicksign/kafka/crypto/samples/stream/keyrepo/SampleProducer.java[tags=produce]
....

##### Stream side

.SampleStream.java
[source,java,indent=0]
....
include::./src/main/java/io/quicksign/kafka/crypto/samples/stream/keyrepo/SampleStream.java[tags=stream]
....


and display

.SampleStream.java
[source,java,indent=0]
....
include::./src/main/java/io/quicksign/kafka/crypto/samples/stream/keyrepo/SampleStream.java[tags=display]
....
